Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
y_pred = classifier.predict(X_test)
print(classification_report(y_test, y_pred, target_names=lb.classes_))
------------------

[0;31m[0m
[0;31mTypeError[0mTraceback (most recent call last)
[0;32m<ipython-input-16-3769236fa3a9>[0m in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [0my_pred[0m [0;34m=[0m [0mclassifier[0m[0;34m.[0m[0mpredict[0m[0;34m([0m[0mX_test[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mprint[0m[0;34m([0m[0mclassification_report[0m[0;34m([0m[0my_test[0m[0;34m,[0m [0my_pred[0m[0;34m,[0m [0mtarget_names[0m[0;34m=[0m[0mlb[0m[0;34m.[0m[0mclasses_[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py[0m in [0;36mclassification_report[0;34m(y_true, y_pred, labels, target_names, sample_weight, digits, output_dict, zero_division)[0m
[1;32m   2361[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2362[0m         [0mlongest_last_line_heading[0m [0;34m=[0m [0;34m"weighted avg"[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2363[0;31m         [0mname_width[0m [0;34m=[0m [0mmax[0m[0;34m([0m[0mlen[0m[0;34m([0m[0mcn[0m[0;34m)[0m [0;32mfor[0m [0mcn[0m [0;32min[0m [0mtarget_names[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2364[0m         [0mwidth[0m [0;34m=[0m [0mmax[0m[0;34m([0m[0mname_width[0m[0;34m,[0m [0mlen[0m[0;34m([0m[0mlongest_last_line_heading[0m[0;34m)[0m[0;34m,[0m [0mdigits[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2365[0m         [0mhead_fmt[0m [0;34m=[0m [0;34m"{:>{width}s} "[0m [0;34m+[0m [0;34m" {:>9}"[0m [0;34m*[0m [0mlen[0m[0;34m([0m[0mheaders[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py[0m in [0;36m<genexpr>[0;34m(.0)[0m
[1;32m   2361[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2362[0m         [0mlongest_last_line_heading[0m [0;34m=[0m [0;34m"weighted avg"[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2363[0;31m         [0mname_width[0m [0;34m=[0m [0mmax[0m[0;34m([0m[0mlen[0m[0;34m([0m[0mcn[0m[0;34m)[0m [0;32mfor[0m [0mcn[0m [0;32min[0m [0mtarget_names[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2364[0m         [0mwidth[0m [0;34m=[0m [0mmax[0m[0;34m([0m[0mname_width[0m[0;34m,[0m [0mlen[0m[0;34m([0m[0mlongest_last_line_heading[0m[0;34m)[0m[0;34m,[0m [0mdigits[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2365[0m         [0mhead_fmt[0m [0;34m=[0m [0;34m"{:>{width}s} "[0m [0;34m+[0m [0;34m" {:>9}"[0m [0;34m*[0m [0mlen[0m[0;34m([0m[0mheaders[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: object of type 'numpy.int64' has no len()
TypeError: object of type 'numpy.int64' has no len()

